<a href="https://colab.research.google.com/github/NGENZIthacien/Individual-work/blob/main/NSHIMIYIMANA_THACIEN_M04578_2025_ASSIGNMENT__NumPy_Pandas.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

**DATA MING FOR BUSINESS INTELLIGENCE ASSIGNMENT

**NumPy & pandas for Beginners**



> Add blockquote

> Add blockquote







**NAME:**NSHIMIYIMANA  THACIEN
Reg. No: M04578/2025


**UNILAK Kigali

*** The assignments Called "Exercises 1, 2, and 3"

In [ ]:
from google.colab import files
uploaded = files.upload()

Saving supermarket_sales.csv to supermarket_sales (1).csv

In [ ]:
import numpy as np

In [ ]:
prices_list = [1200, 3500, 800, 2200, 5000]

In [ ]:
print(prices_list)

[1200, 3500, 800, 2200, 5000]

In [ ]:
prices = np.array([1200, 3500, 800, 2200, 5000])
print(prices)

[1200 3500  800 2200 5000]

In [ ]:
prices_list = [1200, 3500, 800, 2200, 5000]
new_prices_list = []
for price in prices_list:
    new_prices_list.append(price * 1.1)
print(new_prices_list)

[1320.0, 3850.0000000000005, 880.0000000000001, 2420.0, 5500.0]

In [ ]:
new_prices = prices * 1.1

**Exercise 1: NumPy Practice**

1. Create a NumPy array called unit_prices containing these prices:

In [ ]:
import numpy as np
unit_prices = np.array([450, 1200, 3000, 750, 2100, 980])

print(unit_prices)

[ 450 1200 3000  750 2100  980]

2.Print the total (sum) of all unit_prices.

In [ ]:
print(unit_prices.sum())

8480

3. Print the average (mean) unit price.

In [ ]:
print(unit_prices.mean())

1413.3333333333333

4. Apply a 5% price increase to the whole array.

In [ ]:
increased_prices = unit_prices * 1.05

print(increased_prices)

[ 472.5 1260.  3150.   787.5 2205.  1029. ]

5. Find all prices greater than 1000 using a boolean mask.

In [ ]:
mask = unit_prices > 1000

print(mask)

[False  True  True False  True False]

Loading and Exploring Data with pandas

In [ ]:
from google.colab import files
import pandas as pd
import os
if not os.path.exists('supermarket_sales.csv'):
  print('Uploading supermarket_sales.csv...')
  uploaded = files.upload()

df = pd.read_csv('supermarket_sales.csv')
df.head()

         Date Product   Category   Region  UnitPrice  QuantitySold
0  2025-01-01   Sugar    Grocery  Musanze     2113.0          41.0
1  2025-01-01    Soda  Beverages  Musanze      532.0          25.0
2  2025-01-02    Rice     Grains   Rubavu     2481.0           7.0
3  2025-01-02   Bread     Bakery   Rubavu     4844.0           5.0
4  2025-01-02    Soda  Beverages   Kigali     1830.0           6.0

**Exercise 2 : Filtering & Sorting Practice**

6.	Filter df to show only rows where Category is 'Produce'.

In [ ]:
df[df['Category'] == 'Produce']

          Date   Product Category   Region  UnitPrice  QuantitySold
5   2025-01-03  Tomatoes  Produce  Musanze     4492.0           1.0
8   2025-01-04  Tomatoes  Produce   Rubavu     3429.0           2.0
20  2025-01-07    Onions  Produce   Rubavu     2523.0          33.0
24  2025-01-07    Onions  Produce   Rubavu     2277.0           8.0
32  2025-01-11  Tomatoes  Produce     Huye     1590.0          38.0
35  2025-01-12  Tomatoes  Produce     Huye     1280.0           NaN
39  2025-01-13    Onions  Produce   Kigali     4110.0           1.0
43  2025-01-16  Tomatoes  Produce  Musanze     1382.0          40.0
52  2025-01-18  Tomatoes  Produce   Kigali     3541.0          25.0

7.	Filter df to show only rows where QuantitySold is greater than or equal to 20 AND Region is 'Musanze'.

In [ ]:
df[(df['QuantitySold'] >= 20) & (df['Region'] == 'Musanze')]

          Date      Product   Category   Region  UnitPrice  QuantitySold
0   2025-01-01        Sugar    Grocery  Musanze     2113.0          41.0
1   2025-01-01         Soda  Beverages  Musanze      532.0          25.0
34  2025-01-12         Rice     Grains  Musanze     4475.0          28.0
38  2025-01-12  Cooking Oil    Grocery  Musanze        NaN          21.0
43  2025-01-16     Tomatoes    Produce  Musanze     1382.0          40.0
49  2025-01-17        Bread     Bakery  Musanze     2762.0          23.0

8.	Create a new column called 'RevenuePerUnit' that is just equal to UnitPrice (think about why this would always equal UnitPrice before reading further — then in Section 6 we will calculate something more interesting: revenue per category).

In [ ]:
df['RevenuePerUnit'] = df['UnitPrice']

9.	Sort the DataFrame by Date, oldest first, and show the first 10 rows.

In [ ]:
df.sort_values('Date', ascending=True).head(10)

,Date,Product,Category,Region,UnitPrice,QuantitySold,RevenuePerUnit
0,2025-01-01,Sugar,Grocery,Musanze,2113.0,41.0,2113.0
1,2025-01-01,Soda,Beverages,Musanze,532.0,25.0,532.0
2,2025-01-02,Rice,Grains,Rubavu,2481.0,7.0,2481.0
3,2025-01-02,Bread,Bakery,Rubavu,4844.0,5.0,4844.0
4,2025-01-02,Soda,Beverages,Kigali,1830.0,6.0,1830.0
5,2025-01-03,Tomatoes,Produce,Musanze,4492.0,1.0,4492.0
6,2025-01-03,Bread,Bakery,Rubavu,3057.0,12.0,3057.0
7,2025-01-03,Sugar,Grocery,Huye,3710.0,1.0,3710.0
8,2025-01-04,Tomatoes,Produce,Rubavu,3429.0,2.0,3429.0
9,2025-01-04,Soap,Household,Huye,3627.0,28.0,3627.0

10.	Find all rows where Product is either 'Milk', 'Eggs', or 'Soda' using .isin().

In [ ]:
df[df['Product'].isin(['Milk', 'Eggs', 'Soda'])]

,Date,Product,Category,Region,UnitPrice,QuantitySold,RevenuePerUnit
1,2025-01-01,Soda,Beverages,Musanze,532.0,25.0,532.0
4,2025-01-02,Soda,Beverages,Kigali,1830.0,6.0,1830.0
10,2025-01-04,Milk,Dairy,Rubavu,3899.0,6.0,3899.0
12,2025-01-05,Eggs,Dairy,Huye,1267.0,39.0,1267.0
14,2025-01-05,Soda,Beverages,Huye,3969.0,39.0,3969.0
19,2025-01-07,Soda,Beverages,Huye,950.0,11.0,950.0
21,2025-01-07,Soda,Beverages,Rubavu,2998.0,49.0,2998.0
25,2025-01-07,Milk,Dairy,Huye,1854.0,49.0,1854.0
28,2025-01-09,Soda,Beverages,NaN,2477.0,32.0,2477.0
30,2025-01-09,Eggs,Dairy,Huye,1241.0,27.0,1241.0
33,2025-01-11,Eggs,Dairy,Kigali,3701.0,35.0,3701.0
36,2025-01-12,Soda,Beverages,Rubavu,2988.0,4.0,2988.0
37,2025-01-12,Milk,Dairy,Musanze,4527.0,14.0,4527.0
41,2025-01-15,Eggs,Dairy,Rubavu,2814.0,3.0,2814.0
42,2025-01-16,Milk,Dairy,Huye,4229.0,26.0,4229.0
45,2025-01-16,Eggs,Dairy,Rubavu,1967.0,36.0,1967.0
48,2025-01-16,Eggs,Dairy,Rubavu,4492.0,33.0,4492.0
50,2025-01-17,Soda,Beverages,Rubavu,1815.0,16.0,1815.0
51,2025-01-18,Milk,Dairy,Musanze,3614.0,16.0,3614.0
55,2025-01-19,Soda,Beverages,Huye,4143.0,20.0,4143.0
57,2025-01-20,Eggs,Dairy,Rubavu,957.0,35.0,957.0

**Exercice 3 : Grouping & Aggregating Practice**

 14.	Calculate the total QuantitySold for each Category.

In [ ]:
df.groupby('Category')['QuantitySold'].sum()

Category
Bakery       117.0
Beverages    202.0
Dairy        319.0
Grains       141.0
Grocery      186.0
Household    162.0
Produce      148.0
Name: QuantitySold, dtype: float64

15.	Calculate the average TotalRevenue for each Region, sorted from highest to lowest.

In [ ]:
df['TotalRevenue'] = df['UnitPrice'] * df['QuantitySold']
df.groupby('Region')['TotalRevenue'].mean().sort_values(ascending=False)

Region
Huye       80913.428571
Rubavu     54031.833333
Musanze    52418.909091
Kigali     40819.928571
Name: TotalRevenue, dtype: float64

16.	Using .agg() with named aggregation, calculate, for each Region: total revenue, number of sales, and the maximum single-sale revenue.

In [ ]:
df.groupby('Region').agg(
    TotalRevenue=('TotalRevenue', 'sum'),
    NumberOfSales=('TotalRevenue', 'count'),
    MaxSingleSale=('TotalRevenue', 'max')
)

         TotalRevenue  NumberOfSales  MaxSingleSale
Region
Huye        1132788.0             14       155680.0
Kigali       571479.0             14       140751.0
Musanze      576608.0             11       125300.0
Rubavu       972573.0             18       161360.0

17.	Find out which Category appears most frequently in the dataset using value_counts().

In [ ]:
df['Category'].value_counts()

Category
Dairy        12
Grains        9
Beverages     9
Produce       9
Bakery        9
Grocery       7
Household     5
Name: count, dtype: int64

18.	Group by both Category and Region, and find the total revenue for each combination. Use .reset_index() so the result is a flat table.

In [ ]:
df.groupby(['Category', 'Region'])['TotalRevenue'].sum().reset_index()

     Category   Region  TotalRevenue
0      Bakery   Kigali       34658.0
1      Bakery  Musanze      122002.0
2      Bakery   Rubavu      234404.0
3   Beverages     Huye      248101.0
4   Beverages   Kigali       10980.0
5   Beverages  Musanze       13300.0
6   Beverages   Rubavu      187894.0
7       Dairy     Huye      283720.0
8       Dairy   Kigali      129535.0
9       Dairy  Musanze      121202.0
10      Dairy   Rubavu      284379.0
11     Grains   Kigali      203090.0
12     Grains  Musanze      173699.0
13     Grains   Rubavu       41328.0
14    Grocery     Huye       52520.0
15    Grocery   Kigali       67236.0
16    Grocery  Musanze       86633.0
17    Grocery   Rubavu      116235.0
18  Household     Huye      488027.0
19  Household   Kigali       33345.0
20    Produce     Huye       60420.0
21    Produce   Kigali       92635.0
22    Produce  Musanze       59772.0
23    Produce   Rubavu      108333.0

**Exercise 4 : The Manager's Questions**

19.	“What is our total revenue across the entire dataset?” — Calculate a single overall total.

In [ ]:
total_revenue = df['TotalRevenue'].sum()

print(total_revenue)

3332712.0

20.	“Which single product generated the most total revenue, and how much was it?” - Identify the top product and its exact revenue figure.

In [ ]:
revenue_by_product = df.groupby('Product')['TotalRevenue'].sum()

top_product = revenue_by_product.sort_values(ascending=False)

print(top_product.head(1))

Product
Soda    539539.0
Name: TotalRevenue, dtype: float64

21.	“Are sales fairly even across all four regions, or is one region falling behind?” - Calculate total revenue per region and comment on what you notice.

In [ ]:
revenue_by_region = df.groupby('Region')['TotalRevenue'].sum().sort_values(ascending=False)

print(revenue_by_region)

Region
Huye       1132788.0
Rubavu      972573.0
Musanze     576608.0
Kigali      571479.0
Name: TotalRevenue, dtype: float64

22.	“What were our 3 best individual sales days, by total revenue?” — Group by Date and find the top 3 days.

In [ ]:
revenue_by_day = df.groupby('Date')['TotalRevenue'].sum()

print(revenue_by_day.sort_values(ascending=False).head(3))

Date
2025-01-16    549777.0
2025-01-07    533002.0
2025-01-05    378487.0
Name: TotalRevenue, dtype: float64

23.	“Out of all our sales, what percentage came from the Dairy category?” - Hint: you will need total Dairy revenue divided by total overall revenue, multiplied by 100.

In [ ]:
dairy_revenue = df[df['Category'] == 'Dairy']['TotalRevenue'].sum()

total_revenue = df['TotalRevenue'].sum()

dairy_percentage = (dairy_revenue / total_revenue) * 100

print(f'Dairy made up {dairy_percentage:.1f}% of total revenue')

Dairy made up 24.6% of total revenue